### ISSUE TITLE
The Witcher: Enhanced Edition

### ISSUE THREAD

**Issue by skmedix** [SteamDatabase/FileDetectionRuleSets#8]
### SteamDB link to the game

https://steamdb.info/app/20900

### What is it being detected as and what should it be detected as? Any other information?

**Currently detected as:** Unity, GameMaker
**Should be detected as:** Aurora

**Comment by larsiusprime** [comment]
Can you provide me a list of other known Aurora engine games?

**Comment by skmedix** [comment]
https://steamdb.info/app/704450/

**Comment by larsiusprime** [comment]
Okay I added some rules to detect the Aurora engine. We've changed the rules that match for Game Maker to be less aggressive as well to avoid false positives.

The Witcher is legitimately matching for Unity, however, because there is a digital comic in the depot that uses the Unity player. So it should detect Aurora, Unity, next go round.
